# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-30 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('iced', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(default='About me', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='task',
            field=models.IntegerField(null=True),
        ),
    ]
